<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'AptowebDeps\\Twig\\' => array($vendorDir . '/twig/twig/src'),
    'AptowebDeps\\Symfony\\Component\\Uid\\' => array($vendorDir . '/symfony/uid'),
    'AptowebDeps\\Symfony\\Component\\Filesystem\\' => array($vendorDir . '/symfony/filesystem'),
    'AptowebDeps\\Symfony\\Component\\Config\\' => array($vendorDir . '/symfony/config'),
    'AptowebDeps\\Monolog\\' => array($vendorDir . '/monolog/monolog/src/Monolog'),
    'AptowebDeps\\CrowdSec\\Common\\' => array($vendorDir . '/crowdsec/common/src'),
    'AptowebDeps\\CrowdSec\\CapiClient\\' => array($vendorDir . '/crowdsec/capi-client/src'),
);
