<?php

// autoload_real.php @generated by Composer

class ComposerAutoloaderInit80156bc5c43e5fcd684d5ed16d35aa9c
{
    private static $loader;

    public static function loadClassLoader($class)
    {
        if ('AptowebDeps\Composer\Autoload\ClassLoader' === $class) {
            require __DIR__ . '/ClassLoader.php';
        }
    }

    /**
     * @return \AptowebDeps\Composer\Autoload\ClassLoader
     */
    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }

        require __DIR__ . '/platform_check.php';

        spl_autoload_register(array('ComposerAutoloaderInit80156bc5c43e5fcd684d5ed16d35aa9c', 'loadClassLoader'), true, false);
        self::$loader = $loader = new \AptowebDeps\Composer\Autoload\ClassLoader(\dirname(__DIR__));
        spl_autoload_unregister(array('ComposerAutoloaderInit80156bc5c43e5fcd684d5ed16d35aa9c', 'loadClassLoader'));

        require __DIR__ . '/autoload_static.php';
        call_user_func(\AptowebDeps\Composer\Autoload\ComposerStaticInit80156bc5c43e5fcd684d5ed16d35aa9c::getInitializer($loader));

        $loader->register(false);

        $filesToLoad = \AptowebDeps\Composer\Autoload\ComposerStaticInit80156bc5c43e5fcd684d5ed16d35aa9c::$files;
        $requireFile = \Closure::bind(static function ($fileIdentifier, $file) {
            if (empty($GLOBALS['__composer_autoload_files'][$fileIdentifier])) {
                $GLOBALS['__composer_autoload_files'][$fileIdentifier] = true;

                require $file;
            }
        }, null, null);
        foreach ($filesToLoad as $fileIdentifier => $file) {
            $requireFile($fileIdentifier, $file);
        }

        return $loader;
    }
}
