<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    '9e37e3b3b6ede1269b5f09b1e1c8b6bd' => $vendorDir . '/twig/twig/src/Resources/core.php',
    '4627f347e2ab6622eb180b82bd029b8a' => $vendorDir . '/twig/twig/src/Resources/debug.php',
    '9e8bfd3b708fcb3a3fef2484b3482e76' => $vendorDir . '/twig/twig/src/Resources/escaper.php',
    'b87bdc4e3765b430b9c4114598b8b96e' => $vendorDir . '/twig/twig/src/Resources/string_loader.php',
);
