<?php

// autoload_static.php @generated by Composer

namespace AptowebDeps\Composer\Autoload;

class ComposerStaticInitac144f8c9551b4d04769653423964d48
{
    public static $files = array (
        '9e37e3b3b6ede1269b5f09b1e1c8b6bd' => __DIR__ . '/..' . '/twig/twig/src/Resources/core.php',
        '4627f347e2ab6622eb180b82bd029b8a' => __DIR__ . '/..' . '/twig/twig/src/Resources/debug.php',
        '9e8bfd3b708fcb3a3fef2484b3482e76' => __DIR__ . '/..' . '/twig/twig/src/Resources/escaper.php',
        'b87bdc4e3765b430b9c4114598b8b96e' => __DIR__ . '/..' . '/twig/twig/src/Resources/string_loader.php',
    );

    public static $prefixLengthsPsr4 = array (
        'A' =>
        array (
            'AptowebDeps\\Twig\\' => 17,
            'AptowebDeps\\Symfony\\Component\\Uid\\' => 34,
            'AptowebDeps\\Symfony\\Component\\Filesystem\\' => 41,
            'AptowebDeps\\Symfony\\Component\\Config\\' => 37,
            'AptowebDeps\\Monolog\\' => 20,
            'AptowebDeps\\CrowdSec\\Common\\' => 28,
            'AptowebDeps\\CrowdSec\\CapiClient\\' => 32,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'AptowebDeps\\Twig\\' =>
        array (
            0 => __DIR__ . '/..' . '/twig/twig/src',
        ),
        'AptowebDeps\\Symfony\\Component\\Uid\\' =>
        array (
            0 => __DIR__ . '/..' . '/symfony/uid',
        ),
        'AptowebDeps\\Symfony\\Component\\Filesystem\\' =>
        array (
            0 => __DIR__ . '/..' . '/symfony/filesystem',
        ),
        'AptowebDeps\\Symfony\\Component\\Config\\' =>
        array (
            0 => __DIR__ . '/..' . '/symfony/config',
        ),
        'AptowebDeps\\Monolog\\' =>
        array (
            0 => __DIR__ . '/..' . '/monolog/monolog/src/Monolog',
        ),
        'AptowebDeps\\CrowdSec\\Common\\' =>
        array (
            0 => __DIR__ . '/..' . '/crowdsec/common/src',
        ),
        'AptowebDeps\\CrowdSec\\CapiClient\\' =>
        array (
            0 => __DIR__ . '/..' . '/crowdsec/capi-client/src',
        ),
    );

    public static $classMap = array (
        'AptowebDeps\\Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitac144f8c9551b4d04769653423964d48::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitac144f8c9551b4d04769653423964d48::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitac144f8c9551b4d04769653423964d48::$classMap;

        }, null, ClassLoader::class);
    }
}
